#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\fparsec\1.0.3\lib\net40-client\FParsecCS.dll"
#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\fparsec\1.0.3\lib\net40-client\FParsec.dll"
#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\fsharp.core\4.5.2\lib\net45\FSharp.Core.resources.dll"
#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\hopac\0.4.1\lib\net471\Hopac.Core.dll"
#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\hopac\0.4.1\lib\net471\Hopac.Platform.dll"
#r @"C:\Users\ayrat.hudaygulov\.nuget\packages\hopac\0.4.1\lib\net471\Hopac.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Core.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Data.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Drawing.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.IO.Compression.FileSystem.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Numerics.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Runtime.Serialization.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Xml.Linq.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.Xml.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.dll"
#load @"c:\Repos\another-json-parser\src\Another.Json.Parser\obj\Debug\net471\Another.Json.Parser.AssemblyInfo.fs"
#load @"c:\Repos\another-json-parser\src\Another.Json.Parser\jpath.fs"
#load @"c:\Repos\another-json-parser\src\Another.Json.Parser\json.fs"

open JPath

parse "$.abх[?((@.abc > 2) && (@.bgasdasd.asd.tgse ==null))].asdasd"